




#calculate the total revanue genrate by 2 protocal categories in a store.
#ques1
'''calculate the total revenue generated by two protocol categories in a store. 
input:- catergory1_revenue=np.array([500,600,700,550])
input:- catergory2_revenue=np.array([400,700,800,600])'''

import numpy as np

# Input revenues for category 1 and category 2
category1_revenue = np.array([500, 600, 700, 550])
category2_revenue = np.array([400, 700, 800, 600])

# Calculate the total revenue
total_revenue = category1_revenue + category2_revenue

# Display the total revenue
print("Total Revenue by category:", total_revenue)

# Calculate the overall total revenue
overall_total_revenue = np.sum(total_revenue)

# Display the overall total revenue
print("Overall Total Revenue:", overall_total_revenue)
print('===========================================================================')

#ques2

''' Calculate the profit made by a category.
revenue = np.array(10000,12000,11000,10500)
expenses = np.array(4000,5000,4500,4800)'''
import numpy as np

# Input revenue and expenses
revenue = np.array([10000, 12000, 11000, 10500])
expenses = np.array([4000, 5000, 4500, 4800])

# Calculate the profit
profit = revenue - expenses

# Display the profit
print("Profit by category:", profit)

# Calculate the overall profit
overall_profit = np.sum(profit)

# Display the overall profit
print("Overall Profit:", overall_profit)

print('===========================================================================')

   #ques3
'''Determine which product in a store are out of stock (quality is 0).
INPUT:-
inventory = np.array([10,0,5,0,20,0])
OUTPUT:-
Out of stock product :-[0 0 0]'''
import numpy as np
inventory = np.array([10,0,5,0,20,0])
out_of_stock_product =inventory[inventory==0]
print("out of stock product",out_of_stock_product)

print('===========================================================================')
#ques4
'''Calculate the total cost of items in a shopping cart , considering the quantity and price per item
    INPUT:- Quantity =np.array([2,3,4,1])
    price_per_item=np.array([10,5,8,12])'''
import numpy as np

# Input quantity and price per item
quantity = np.array([2, 3, 4, 1])
price_per_item = np.array([10, 5, 8, 12])

# Calculate the total cost for each item
total_cost_per_item = quantity * price_per_item

# Calculate the overall total cost
total_cost = np.sum(total_cost_per_item)

# Display the total cost per item
print("Total cost per item:", total_cost_per_item)

# Display the overall total cost
print("Overall Total Cost:", total_cost)
